# 快捷键配置
# 可用变量: {name} 全名, {surname} 姓, {given_name} 名
hotkeys:
  "alt+1":
    name: "学生"
    replies:
      - "谢谢，{name}同学过年好！祝新春快乐，马年大吉，新年成果多多！"

  "alt+2":
    name: "毕业学生/青年教师"
    replies:
      - "谢谢，{surname}老师新春快乐啊！祝马年大吉，新年成果多多！"

  "alt+3":
    name: "同行资深教授"
    replies:
      - "谢谢，祝{surname}老师新春快乐，马年大吉！新的一年请您多指教！"

  "alt+4":
    name: "熟人"
    replies:
      - "{name}新年好啊！祝马年大吉，万事如意！"

  "alt+5":
    name: "其他"
    replies:
      - "谢谢，祝马年大吉，万事如意！"      